### ISSUE TITLE
Fatal Python error: deallocating None

### ISSUE THREAD

**Issue by irishswguy** [Dynamsoft/barcode-reader-python-samples#36]
We are facing a problem ( Looks like a memory leak ) that when we use it to read lots of images ( We use it in real time ) it causes a crash.

We get this error :
Fatal Python error: deallocating None
Python runtime state: initialized

Current thread 0x00007f110c588740 (most recent call first):
  File "debug.py", line 14 in <module>
Aborted (core dumped)

This can happen after 700 uses but cal also take up to 8000 uses before it happens. It appears random.

We have tested this on 3 different PC's with the following test code and we always get the crash.

`import cv2
from dbr import *

json_file = r"Please input your own template path"
license_key = "t0070fQAAAGaeApMwKH9QQqOMMKYqbpPriea3LzpS5GgmGMt9Cf2DUrmrSErh6JDgXPrYyKjIwirB+VFpBavnrn8qJDf6qaYbhw=="
reader = BarcodeReader()
reader.init_license(license_key)

image = cv2.imread("1.jpg")

i=0
while 0 == 0:
text_results = reader.decode_buffer(image)
     DataMatrixResult = len(text_results)      
     print("loop_number = ",i)
     i=i+1`

**Comment by yushulx** [comment]
@irishswguy 

- What OS are you using?

- What is your Python version?

- What is your barcode SDK version?

- Can you provide your image? I've tested the code with my DataMatrix image on Windows 10. There's no memory leak.
