### ISSUE TITLE
using dbr for detecting QR code coordinates 

### ISSUE THREAD

**Issue by zfarahi** [Dynamsoft/barcode-reader-python-samples#45]
i want to ask if i install the dbr code "pip install dbr", to only use for detecting qr code and get the coordinates of it is this free ?
i am not sure because i am not using any "license_key" for detecting qr code and it coordinate. could you please explain what is on the pay price of dbr qr code.

**Comment by DMGithubPublisher** [comment]
It's not free. Please contact sales@dynamsoft.com or visit https://www.dynamsoft.com/store/dynamsoft-barcode-reader to ask for a quote

**Comment by coheedandcambria** [comment]
Closing this issue
