### ISSUE TITLE
Fatal Python error: deallocating None / Process finished with exit code 137

### ISSUE THREAD

**Issue by V4570** [Dynamsoft/barcode-reader-python-samples#47]
Hi Dynamsoft team. I work for Zenus that provides analytics solutions for events, which includes QR code scanning. We have obtained a number of Dynamsoft QR code scanning licenses for our devices in order to provide this service, and are now facing an issue.
We use the video mode of the library ( dbr.start_video_mode(**params) ), in order to have both a live feed and asynchronous QR code decoding. What happens is that after some time, probably due to a memory leak we get the error of the title [Fatal Python error: deallocating None].
When running your python example, we get a similar error after some time that indicates issues with accessing memory [Process finished with exit code 137].

This doesn't have to do with QR code version, as it happens without presenting any QR codes during runtime after some time.

I have seen that there was an update regarding this, but it seems that it wasn't completely solved. Bellow you can find information about our setup.
- Platform: Jetson Xavier NX
- OS: balenalib/jetson-xavier-nx-devkit-emmc-ubuntu (bionic)
- Python version: 3.6.9
- DBR library version: (latest) 9.6.20

Any help resolving this, or any updates on a fix would be greatly appreciated.

**Comment by jeanwolframpixel** [comment]
I also get the same error after around 20000 read codes. 
I am not using video mode, so its not time dependent but related to the number of read codes, happens at the exact same number of read codes everytime.

"Fatal Python error: deallocating None"

When i try to delete **reader_results** ->"reader_results = reader.decode_buffer(image)",
like so: "**del reader_results**", i get the exact same error but on this line where i try to delete **reader_results**

Also after the exact same number of read codes like before.

Setup:
- Windows 11
- python 3.8
- DBR version 8.6

**Comment by jeanwolframpixel** [comment]
Ok DBR Version 8.8 fixes the Problem for me

**Comment by DMGithubPublisher** [comment]
The issue has been fixed in version 9.6.30
